language: python
python:
  - "3.4"
  # - "3.5"
  # - "3.6"

install:
  - pip install .
  - pip install .[testing]

script: pytest -vs

deploy:
  provider: pypi
  user: myuser
  password: mypassword
  on:
    branch: master
