language: python
python:
  - "3.4"
  # - "3.5"
  # - "3.6"

install:
  - pip install .
  - pip install .[testing]

script: pytest -vs

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-999].[0-999].[0-999](rc[0-999])?$
