language: python
python:
  - "3.4"
  # - "3.5"
  # - "3.6"

install:
  - pip install .
  - pip install .[testing]

script: pytest -vs

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: master
    # tags: true
